<?php
namespace App\Helpers;

class CountryData
{
    public static function getList()
    {
        return $countries = [
            ['shortcut' => 'AD', 'country_name' => 'Andorra', 'country_code' => '+376', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'AE', 'country_name' => 'United Arab Emirates', 'country_code' => '+971', 'currency' => 'AED', 'currency_rate' => 0.012],
            ['shortcut' => 'AF', 'country_name' => 'Afghanistan', 'country_code' => '+93', 'currency' => 'AFN', 'currency_rate' => 0.028],
            ['shortcut' => 'AG', 'country_name' => 'Antigua and Barbuda', 'country_code' => '+1-268', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'AI', 'country_name' => 'Anguilla', 'country_code' => '+1-264', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'AL', 'country_name' => 'Albania', 'country_code' => '+355', 'currency' => 'ALL', 'currency_rate' => 0.086],
            ['shortcut' => 'AM', 'country_name' => 'Armenia', 'country_code' => '+374', 'currency' => 'AMD', 'currency_rate' => 5.25],
            ['shortcut' => 'AO', 'country_name' => 'Angola', 'country_code' => '+244', 'currency' => 'AOA', 'currency_rate' => 0.16],
            ['shortcut' => 'AR', 'country_name' => 'Argentina', 'country_code' => '+54', 'currency' => 'ARS', 'currency_rate' => 0.23],
            ['shortcut' => 'AS', 'country_name' => 'American Samoa', 'country_code' => '+1-684', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'AT', 'country_name' => 'Austria', 'country_code' => '+43', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'AU', 'country_name' => 'Australia', 'country_code' => '+61', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'AW', 'country_name' => 'Aruba', 'country_code' => '+297', 'currency' => 'AWG', 'currency_rate' => 0.018],
            ['shortcut' => 'AX', 'country_name' => 'Åland Islands', 'country_code' => '+358', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'AZ', 'country_name' => 'Azerbaijan', 'country_code' => '+994', 'currency' => 'AZN', 'currency_rate' => 0.015],
            ['shortcut' => 'BA', 'country_name' => 'Bosnia and Herzegovina', 'country_code' => '+387', 'currency' => 'BAM', 'currency_rate' => 0.0056],
            ['shortcut' => 'BB', 'country_name' => 'Barbados', 'country_code' => '+1-246', 'currency' => 'BBD', 'currency_rate' => 0.0053],
            ['shortcut' => 'BD', 'country_name' => 'Bangladesh', 'country_code' => '+880', 'currency' => 'BDT', 'currency_rate' => 0.023],
            ['shortcut' => 'BE', 'country_name' => 'Belgium', 'country_code' => '+32', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'BF', 'country_name' => 'Burkina Faso', 'country_code' => '+226', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'BG', 'country_name' => 'Bulgaria', 'country_code' => '+359', 'currency' => 'BGN', 'currency_rate' => 0.021],
            ['shortcut' => 'BH', 'country_name' => 'Bahrain', 'country_code' => '+973', 'currency' => 'BHD', 'currency_rate' => 0.004],
            ['shortcut' => 'BI', 'country_name' => 'Burundi', 'country_code' => '+257', 'currency' => 'BIF', 'currency_rate' => 0.023],
            ['shortcut' => 'BJ', 'country_name' => 'Benin', 'country_code' => '+229', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'BL', 'country_name' => 'Saint Barthélemy', 'country_code' => '+590', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'BM', 'country_name' => 'Bermuda', 'country_code' => '+1-441', 'currency' => 'BMD', 'currency_rate' => 0.019],
            ['shortcut' => 'BN', 'country_name' => 'Brunei', 'country_code' => '+673', 'currency' => 'BND', 'currency_rate' => 0.015],
            ['shortcut' => 'BO', 'country_name' => 'Bolivia', 'country_code' => '+591', 'currency' => 'BOB', 'currency_rate' => 0.035],
            ['shortcut' => 'BQ', 'country_name' => 'Bonaire, Sint Eustatius and Saba', 'country_code' => '+599', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'BR', 'country_name' => 'Brazil', 'country_code' => '+55', 'currency' => 'BRL', 'currency_rate' => 0.002],
            ['shortcut' => 'BS', 'country_name' => 'Bahamas', 'country_code' => '+1-242', 'currency' => 'BSD', 'currency_rate' => 0.019],
            ['shortcut' => 'BT', 'country_name' => 'Bhutan', 'country_code' => '+975', 'currency' => 'BTN', 'currency_rate' => 0.024],
            ['shortcut' => 'BV', 'country_name' => 'Bouvet Island', 'country_code' => '+47', 'currency' => 'NOK', 'currency_rate' => 0.11],
            ['shortcut' => 'BW', 'country_name' => 'Botswana', 'country_code' => '+267', 'currency' => 'BWP', 'currency_rate' => 0.27],
            ['shortcut' => 'BY', 'country_name' => 'Belarus', 'country_code' => '+375', 'currency' => 'BYN', 'currency_rate' => 0.012],
            ['shortcut' => 'BZ', 'country_name' => 'Belize', 'country_code' => '+501', 'currency' => 'BZD', 'currency_rate' => 0.02],
            ['shortcut' => 'CA', 'country_name' => 'Canada', 'country_code' => '+1', 'currency' => 'CAD', 'currency_rate' => 0.014],
            ['shortcut' => 'CC', 'country_name' => 'Cocos (Keeling) Islands', 'country_code' => '+61', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'CD', 'country_name' => 'Democratic Republic of the Congo', 'country_code' => '+243', 'currency' => 'CDF', 'currency_rate' => 0.045],
            ['shortcut' => 'CF', 'country_name' => 'Central African Republic', 'country_code' => '+236', 'currency' => 'XAF', 'currency_rate' => 0.06],
            ['shortcut' => 'CG', 'country_name' => 'Republic of the Congo', 'country_code' => '+242', 'currency' => 'XAF', 'currency_rate' => 0.06],
            ['shortcut' => 'CH', 'country_name' => 'Switzerland', 'country_code' => '+41', 'currency' => 'CHF', 'currency_rate' => 0.011],
            ['shortcut' => 'CI', 'country_name' => 'Ivory Coast', 'country_code' => '+225', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'CK', 'country_name' => 'Cook Islands', 'country_code' => '+682', 'currency' => 'NZD', 'currency_rate' => 0.013],
            ['shortcut' => 'CL', 'country_name' => 'Chile', 'country_code' => '+56', 'currency' => 'CLP', 'currency_rate' => 0.019],
            ['shortcut' => 'CM', 'country_name' => 'Cameroon', 'country_code' => '+237', 'currency' => 'XAF', 'currency_rate' => 0.06],
            ['shortcut' => 'CN', 'country_name' => 'China', 'country_code' => '+86', 'currency' => 'CNY', 'currency_rate' => 0.13],
            ['shortcut' => 'CO', 'country_name' => 'Colombia', 'country_code' => '+57', 'currency' => 'COP', 'currency_rate' => 0.0028],
            ['shortcut' => 'CR', 'country_name' => 'Costa Rica', 'country_code' => '+506', 'currency' => 'CRC', 'currency_rate' => 0.0018],
            ['shortcut' => 'CU', 'country_name' => 'Cuba', 'country_code' => '+53', 'currency' => 'CUP', 'currency_rate' => 0.038],
            ['shortcut' => 'CV', 'country_name' => 'Cabo Verde', 'country_code' => '+238', 'currency' => 'CVE', 'currency_rate' => 0.019],
            ['shortcut' => 'CW', 'country_name' => 'Curaçao', 'country_code' => '+599', 'currency' => 'ANG', 'currency_rate' => 0.018],
            ['shortcut' => 'CX', 'country_name' => 'Christmas Island', 'country_code' => '+61', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'CY', 'country_name' => 'Cyprus', 'country_code' => '+357', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'CZ', 'country_name' => 'Czech Republic', 'country_code' => '+420', 'currency' => 'CZK', 'currency_rate' => 0.046],
            ['shortcut' => 'DE', 'country_name' => 'Germany', 'country_code' => '+49', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'DJ', 'country_name' => 'Djibouti', 'country_code' => '+253', 'currency' => 'DJF', 'currency_rate' => 0.11],
            ['shortcut' => 'DK', 'country_name' => 'Denmark', 'country_code' => '+45', 'currency' => 'DKK', 'currency_rate' => 0.085],
            ['shortcut' => 'DM', 'country_name' => 'Dominica', 'country_code' => '+1-767', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'DO', 'country_name' => 'Dominican Republic', 'country_code' => '+1-809', 'currency' => 'DOP', 'currency_rate' => 0.033],
            ['shortcut' => 'DZ', 'country_name' => 'Algeria', 'country_code' => '+213', 'currency' => 'DZD', 'currency_rate' => 0.024],
            ['shortcut' => 'EC', 'country_name' => 'Ecuador', 'country_code' => '+593', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'EE', 'country_name' => 'Estonia', 'country_code' => '+372', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'EG', 'country_name' => 'Egypt', 'country_code' => '+20', 'currency' => 'EGP', 'currency_rate' => 0.52],
            ['shortcut' => 'EH', 'country_name' => 'Western Sahara', 'country_code' => '+212', 'currency' => 'MAD', 'currency_rate' => 0.099],
            ['shortcut' => 'ER', 'country_name' => 'Eritrea', 'country_code' => '+291', 'currency' => 'ERN', 'currency_rate' => 0.15],
            ['shortcut' => 'ES', 'country_name' => 'Spain', 'country_code' => '+34', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'ET', 'country_name' => 'Ethiopia', 'country_code' => '+251', 'currency' => 'ETB', 'currency_rate' => 0.048],
            ['shortcut' => 'FI', 'country_name' => 'Finland', 'country_code' => '+358', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'FJ', 'country_name' => 'Fiji', 'country_code' => '+679', 'currency' => 'FJD', 'currency_rate' => 0.021],
            ['shortcut' => 'FM', 'country_name' => 'Micronesia', 'country_code' => '+691', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'FO', 'country_name' => 'Faroe Islands', 'country_code' => '+298', 'currency' => 'DKK', 'currency_rate' => 0.085],
            ['shortcut' => 'FR', 'country_name' => 'France', 'country_code' => '+33', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'GA', 'country_name' => 'Gabon', 'country_code' => '+241', 'currency' => 'XAF', 'currency_rate' => 0.06],
            ['shortcut' => 'GB', 'country_name' => 'United Kingdom', 'country_code' => '+44', 'currency' => 'GBP', 'currency_rate' => 0.008],
            ['shortcut' => 'GD', 'country_name' => 'Grenada', 'country_code' => '+1-473', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'GE', 'country_name' => 'Georgia', 'country_code' => '+995', 'currency' => 'GEL', 'currency_rate' => 0.031],
            ['shortcut' => 'GF', 'country_name' => 'French Guiana', 'country_code' => '+594', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'GG', 'country_name' => 'Guernsey', 'country_code' => '+44-1481', 'currency' => 'GBP', 'currency_rate' => 0.008],
            ['shortcut' => 'GH', 'country_name' => 'Ghana', 'country_code' => '+233', 'currency' => 'GHS', 'currency_rate' => 0.12],
            ['shortcut' => 'GI', 'country_name' => 'Gibraltar', 'country_code' => '+350', 'currency' => 'GIP', 'currency_rate' => 0.008],
            ['shortcut' => 'GL', 'country_name' => 'Greenland', 'country_code' => '+299', 'currency' => 'DKK', 'currency_rate' => 0.085],
            ['shortcut' => 'GM', 'country_name' => 'Gambia', 'country_code' => '+220', 'currency' => 'GMD', 'currency_rate' => 0.018],
            ['shortcut' => 'GN', 'country_name' => 'Guinea', 'country_code' => '+224', 'currency' => 'GNF', 'currency_rate' => 0.027],
            ['shortcut' => 'GP', 'country_name' => 'Guadeloupe', 'country_code' => '+590', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'GQ', 'country_name' => 'Equatorial Guinea', 'country_code' => '+240', 'currency' => 'XAF', 'currency_rate' => 0.06],
            ['shortcut' => 'GR', 'country_name' => 'Greece', 'country_code' => '+30', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'GT', 'country_name' => 'Guatemala', 'country_code' => '+502', 'currency' => 'GTQ', 'currency_rate' => 0.13],
            ['shortcut' => 'GU', 'country_name' => 'Guam', 'country_code' => '+1-671', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'GW', 'country_name' => 'Guinea-Bissau', 'country_code' => '+245', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'GY', 'country_name' => 'Guyana', 'country_code' => '+592', 'currency' => 'GYD', 'currency_rate' => 0.038],
            ['shortcut' => 'HK', 'country_name' => 'Hong Kong', 'country_code' => '+852', 'currency' => 'HKD', 'currency_rate' => 0.014],
            ['shortcut' => 'HM', 'country_name' => 'Heard Island and McDonald Islands', 'country_code' => '+61', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'HN', 'country_name' => 'Honduras', 'country_code' => '+504', 'currency' => 'HNL', 'currency_rate' => 0.079],
            ['shortcut' => 'HR', 'country_name' => 'Croatia', 'country_code' => '+385', 'currency' => 'HRK', 'currency_rate' => 0.017],
            ['shortcut' => 'HT', 'country_name' => 'Haiti', 'country_code' => '+509', 'currency' => 'HTG', 'currency_rate' => 0.1],
            ['shortcut' => 'HU', 'country_name' => 'Hungary', 'country_code' => '+36', 'currency' => 'HUF', 'currency_rate' => 0.038],
            ['shortcut' => 'ID', 'country_name' => 'Indonesia', 'country_code' => '+62', 'currency' => 'IDR', 'currency_rate' => 0.000065],
            ['shortcut' => 'IE', 'country_name' => 'Ireland', 'country_code' => '+353', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'IL', 'country_name' => 'Israel', 'country_code' => '+972', 'currency' => 'ILS', 'currency_rate' => 0.0078],
            ['shortcut' => 'IM', 'country_name' => 'Isle of Man', 'country_code' => '+44-1624', 'currency' => 'GBP', 'currency_rate' => 0.008],
            ['shortcut' => 'IN', 'country_name' => 'India', 'country_code' => '+91', 'currency' => 'INR', 'currency_rate' => 0.012],
            ['shortcut' => 'IO', 'country_name' => 'British Indian Ocean Territory', 'country_code' => '+246', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'IQ', 'country_name' => 'Iraq', 'country_code' => '+964', 'currency' => 'IQD', 'currency_rate' => 0.013],
            ['shortcut' => 'IR', 'country_name' => 'Iran', 'country_code' => '+98', 'currency' => 'IRR', 'currency_rate' => 0.0026],
            ['shortcut' => 'IS', 'country_name' => 'Iceland', 'country_code' => '+354', 'currency' => 'ISK', 'currency_rate' => 0.06],
            ['shortcut' => 'IT', 'country_name' => 'Italy', 'country_code' => '+39', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'JE', 'country_name' => 'Jersey', 'country_code' => '+44-1534', 'currency' => 'GBP', 'currency_rate' => 0.008],
            ['shortcut' => 'JM', 'country_name' => 'Jamaica', 'country_code' => '+1-876', 'currency' => 'JMD', 'currency_rate' => 0.13],
            ['shortcut' => 'JO', 'country_name' => 'Jordan', 'country_code' => '+962', 'currency' => 'JOD', 'currency_rate' => 0.014],
            ['shortcut' => 'JP', 'country_name' => 'Japan', 'country_code' => '+81', 'currency' => 'JPY', 'currency_rate' => 0.071],
            ['shortcut' => 'KE', 'country_name' => 'Kenya', 'country_code' => '+254', 'currency' => 'KES', 'currency_rate' => 0.067],
            ['shortcut' => 'KG', 'country_name' => 'Kyrgyzstan', 'country_code' => '+996', 'currency' => 'KGS', 'currency_rate' => 0.066],
            ['shortcut' => 'KH', 'country_name' => 'Cambodia', 'country_code' => '+855', 'currency' => 'KHR', 'currency_rate' => 0.00025],
            ['shortcut' => 'KI', 'country_name' => 'Kiribati', 'country_code' => '+686', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'KM', 'country_name' => 'Comoros', 'country_code' => '+269', 'currency' => 'KMF', 'currency_rate' => 0.012],
            ['shortcut' => 'KN', 'country_name' => 'Saint Kitts and Nevis', 'country_code' => '+1-869', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'KP', 'country_name' => 'North Korea', 'country_code' => '+850', 'currency' => 'KPW', 'currency_rate' => 0.11],
            ['shortcut' => 'KR', 'country_name' => 'South Korea', 'country_code' => '+82', 'currency' => 'KRW', 'currency_rate' => 0.00076],
            ['shortcut' => 'KW', 'country_name' => 'Kuwait', 'country_code' => '+965', 'currency' => 'KWD', 'currency_rate' => 0.0063],
            ['shortcut' => 'KY', 'country_name' => 'Cayman Islands', 'country_code' => '+1-345', 'currency' => 'KYD', 'currency_rate' => 0.017],
            ['shortcut' => 'KZ', 'country_name' => 'Kazakhstan', 'country_code' => '+7', 'currency' => 'KZT', 'currency_rate' => 0.0022],
            ['shortcut' => 'LA', 'country_name' => 'Laos', 'country_code' => '+856', 'currency' => 'LAK', 'currency_rate' => 0.000096],
            ['shortcut' => 'LB', 'country_name' => 'Lebanon', 'country_code' => '+961', 'currency' => 'LBP', 'currency_rate' => 0.00063],
            ['shortcut' => 'LC', 'country_name' => 'Saint Lucia', 'country_code' => '+1-758', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'LI', 'country_name' => 'Liechtenstein', 'country_code' => '+423', 'currency' => 'CHF', 'currency_rate' => 0.011],
            ['shortcut' => 'LK', 'country_name' => 'Sri Lanka', 'country_code' => '+94', 'currency' => 'LKR', 'currency_rate' => 0.049],
            ['shortcut' => 'LR', 'country_name' => 'Liberia', 'country_code' => '+231', 'currency' => 'LRD', 'currency_rate' => 0.0024],
            ['shortcut' => 'LS', 'country_name' => 'Lesotho', 'country_code' => '+266', 'currency' => 'LSL', 'currency_rate' => 0.27],
            ['shortcut' => 'LT', 'country_name' => 'Lithuania', 'country_code' => '+370', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'LU', 'country_name' => 'Luxembourg', 'country_code' => '+352', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'LV', 'country_name' => 'Latvia', 'country_code' => '+371', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'LY', 'country_name' => 'Libya', 'country_code' => '+218', 'currency' => 'LYD', 'currency_rate' => 0.0048],
            ['shortcut' => 'MA', 'country_name' => 'Morocco', 'country_code' => '+212', 'currency' => 'MAD', 'currency_rate' => 0.099],
            ['shortcut' => 'MC', 'country_name' => 'Monaco', 'country_code' => '+377', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'MD', 'country_name' => 'Moldova', 'country_code' => '+373', 'currency' => 'MDL', 'currency_rate' => 0.053],
            ['shortcut' => 'ME', 'country_name' => 'Montenegro', 'country_code' => '+382', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'MF', 'country_name' => 'Saint Martin', 'country_code' => '+590', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'MG', 'country_name' => 'Madagascar', 'country_code' => '+261', 'currency' => 'MGA', 'currency_rate' => 0.00023],
            ['shortcut' => 'MH', 'country_name' => 'Marshall Islands', 'country_code' => '+692', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'MK', 'country_name' => 'North Macedonia', 'country_code' => '+389', 'currency' => 'MKD', 'currency_rate' => 0.019],
            ['shortcut' => 'ML', 'country_name' => 'Mali', 'country_code' => '+223', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'MM', 'country_name' => 'Myanmar', 'country_code' => '+95', 'currency' => 'MMK', 'currency_rate' => 0.000045],
            ['shortcut' => 'MN', 'country_name' => 'Mongolia', 'country_code' => '+976', 'currency' => 'MNT', 'currency_rate' => 0.031],
            ['shortcut' => 'MO', 'country_name' => 'Macau', 'country_code' => '+853', 'currency' => 'MOP', 'currency_rate' => 0.024],
            ['shortcut' => 'MP', 'country_name' => 'Northern Mariana Islands', 'country_code' => '+1-670', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'MQ', 'country_name' => 'Martinique', 'country_code' => '+596', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'MR', 'country_name' => 'Mauritania', 'country_code' => '+222', 'currency' => 'MRU', 'currency_rate' => 0.027],
            ['shortcut' => 'MS', 'country_name' => 'Montserrat', 'country_code' => '+1-664', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'MT', 'country_name' => 'Malta', 'country_code' => '+356', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'MU', 'country_name' => 'Mauritius', 'country_code' => '+230', 'currency' => 'MUR', 'currency_rate' => 0.025],
            ['shortcut' => 'MV', 'country_name' => 'Maldives', 'country_code' => '+960', 'currency' => 'MVR', 'currency_rate' => 0.065],
            ['shortcut' => 'MW', 'country_name' => 'Malawi', 'country_code' => '+265', 'currency' => 'MWK', 'currency_rate' => 0.0011],
            ['shortcut' => 'MX', 'country_name' => 'Mexico', 'country_code' => '+52', 'currency' => 'MXN', 'currency_rate' => 0.055],
            ['shortcut' => 'MY', 'country_name' => 'Malaysia', 'country_code' => '+60', 'currency' => 'MYR', 'currency_rate' => 0.23],
            ['shortcut' => 'MZ', 'country_name' => 'Mozambique', 'country_code' => '+258', 'currency' => 'MZN', 'currency_rate' => 0.016],
            ['shortcut' => 'NA', 'country_name' => 'Namibia', 'country_code' => '+264', 'currency' => 'NAD', 'currency_rate' => 0.27],
            ['shortcut' => 'NC', 'country_name' => 'New Caledonia', 'country_code' => '+687', 'currency' => 'XPF', 'currency_rate' => 0.017],
            ['shortcut' => 'NE', 'country_name' => 'Niger', 'country_code' => '+227', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'NF', 'country_name' => 'Norfolk Island', 'country_code' => '+672', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'NG', 'country_name' => 'Nigeria', 'country_code' => '+234', 'currency' => 'NGN', 'currency_rate' => 0.0013],
            ['shortcut' => 'NI', 'country_name' => 'Nicaragua', 'country_code' => '+505', 'currency' => 'NIO', 'currency_rate' => 0.028],
            ['shortcut' => 'NL', 'country_name' => 'Netherlands', 'country_code' => '+31', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'NO', 'country_name' => 'Norway', 'country_code' => '+47', 'currency' => 'NOK', 'currency_rate' => 0.092],
            ['shortcut' => 'NP', 'country_name' => 'Nepal', 'country_code' => '+977', 'currency' => 'NPR', 'currency_rate' => 0.0075],
            ['shortcut' => 'NR', 'country_name' => 'Nauru', 'country_code' => '+674', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'NU', 'country_name' => 'Niue', 'country_code' => '+683', 'currency' => 'NZD', 'currency_rate' => 0.022],
            ['shortcut' => 'NZ', 'country_name' => 'New Zealand', 'country_code' => '+64', 'currency' => 'NZD', 'currency_rate' => 0.022],
            ['shortcut' => 'OM', 'country_name' => 'Oman', 'country_code' => '+968', 'currency' => 'OMR', 'currency_rate' => 0.0026],
            ['shortcut' => 'PA', 'country_name' => 'Panama', 'country_code' => '+507', 'currency' => 'PAB', 'currency_rate' => 0.019],
            ['shortcut' => 'PE', 'country_name' => 'Peru', 'country_code' => '+51', 'currency' => 'PEN', 'currency_rate' => 0.052],
            ['shortcut' => 'PF', 'country_name' => 'French Polynesia', 'country_code' => '+689', 'currency' => 'XPF', 'currency_rate' => 0.017],
            ['shortcut' => 'PG', 'country_name' => 'Papua New Guinea', 'country_code' => '+675', 'currency' => 'PGK', 'currency_rate' => 0.028],
            ['shortcut' => 'PH', 'country_name' => 'Philippines', 'country_code' => '+63', 'currency' => 'PHP', 'currency_rate' => 0.018],
            ['shortcut' => 'PK', 'country_name' => 'Pakistan', 'country_code' => '+92', 'currency' => 'PKR', 'currency_rate' => 0.0045],
            ['shortcut' => 'PL', 'country_name' => 'Poland', 'country_code' => '+48', 'currency' => 'PLN', 'currency_rate' => 0.024],
            ['shortcut' => 'PM', 'country_name' => 'Saint Pierre and Miquelon', 'country_code' => '+508', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'PN', 'country_name' => 'Pitcairn', 'country_code' => '+64', 'currency' => 'NZD', 'currency_rate' => 0.022],
            ['shortcut' => 'PR', 'country_name' => 'Puerto Rico', 'country_code' => '+1-787', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'PT', 'country_name' => 'Portugal', 'country_code' => '+351', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'PW', 'country_name' => 'Palau', 'country_code' => '+680', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'PY', 'country_name' => 'Paraguay', 'country_code' => '+595', 'currency' => 'PYG', 'currency_rate' => 0.00014],
            ['shortcut' => 'QA', 'country_name' => 'Qatar', 'country_code' => '+974', 'currency' => 'QAR', 'currency_rate' => 0.0087],
            ['shortcut' => 'RE', 'country_name' => 'Réunion', 'country_code' => '+262', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'RO', 'country_name' => 'Romania', 'country_code' => '+40', 'currency' => 'RON', 'currency_rate' => 0.021],
            ['shortcut' => 'RS', 'country_name' => 'Serbia', 'country_code' => '+381', 'currency' => 'RSD', 'currency_rate' => 0.044],
            ['shortcut' => 'RU', 'country_name' => 'Russia', 'country_code' => '+7', 'currency' => 'RUB', 'currency_rate' => 0.011],
            ['shortcut' => 'RW', 'country_name' => 'Rwanda', 'country_code' => '+250', 'currency' => 'RWF', 'currency_rate' => 0.0011],
            ['shortcut' => 'SA', 'country_name' => 'Saudi Arabia', 'country_code' => '+966', 'currency' => 'SAR', 'currency_rate' => 0.013],
            ['shortcut' => 'SB', 'country_name' => 'Solomon Islands', 'country_code' => '+677', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'SC', 'country_name' => 'Seychelles', 'country_code' => '+248', 'currency' => 'SCR', 'currency_rate' => 0.015],
            ['shortcut' => 'SD', 'country_name' => 'Sudan', 'country_code' => '+249', 'currency' => 'SDG', 'currency_rate' => 0.0023],
            ['shortcut' => 'SE', 'country_name' => 'Sweden', 'country_code' => '+46', 'currency' => 'SEK', 'currency_rate' => 0.093],
            ['shortcut' => 'SG', 'country_name' => 'Singapore', 'country_code' => '+65', 'currency' => 'SGD', 'currency_rate' => 0.019],
            ['shortcut' => 'SH', 'country_name' => 'Saint Helena', 'country_code' => '+290', 'currency' => 'SHP', 'currency_rate' => 0.008],
            ['shortcut' => 'SI', 'country_name' => 'Slovenia', 'country_code' => '+386', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'SJ', 'country_name' => 'Svalbard and Jan Mayen', 'country_code' => '+47', 'currency' => 'NOK', 'currency_rate' => 0.092],
            ['shortcut' => 'SK', 'country_name' => 'Slovakia', 'country_code' => '+421', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'SL', 'country_name' => 'Sierra Leone', 'country_code' => '+232', 'currency' => 'SLL', 'currency_rate' => 0.000046],
            ['shortcut' => 'SM', 'country_name' => 'San Marino', 'country_code' => '+378', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'SN', 'country_name' => 'Senegal', 'country_code' => '+221', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'SO', 'country_name' => 'Somalia', 'country_code' => '+252', 'currency' => 'SOS', 'currency_rate' => 0.0017],
            ['shortcut' => 'SR', 'country_name' => 'Suriname', 'country_code' => '+597', 'currency' => 'SRD', 'currency_rate' => 0.14],
            ['shortcut' => 'SS', 'country_name' => 'South Sudan', 'country_code' => '+211', 'currency' => 'SSP', 'currency_rate' => 0.0017],
            ['shortcut' => 'ST', 'country_name' => 'Sao Tome and Principe', 'country_code' => '+239', 'currency' => 'STN', 'currency_rate' => 0.048],
            ['shortcut' => 'SV', 'country_name' => 'El Salvador', 'country_code' => '+503', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'SX', 'country_name' => 'Sint Maarten', 'country_code' => '+1-721', 'currency' => 'ANG', 'currency_rate' => 0.027],
            ['shortcut' => 'SY', 'country_name' => 'Syria', 'country_code' => '+963', 'currency' => 'SYP', 'currency_rate' => 0.0018],
            ['shortcut' => 'SZ', 'country_name' => 'Eswatini', 'country_code' => '+268', 'currency' => 'SZL', 'currency_rate' => 0.051],
            ['shortcut' => 'TC', 'country_name' => 'Turks and Caicos Islands', 'country_code' => '+1-649', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'TD', 'country_name' => 'Chad', 'country_code' => '+235', 'currency' => 'XAF', 'currency_rate' => 0.0018],
            ['shortcut' => 'TF', 'country_name' => 'French Southern Territories', 'country_code' => '+262', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'TG', 'country_name' => 'Togo', 'country_code' => '+228', 'currency' => 'XOF', 'currency_rate' => 0.06],
            ['shortcut' => 'TH', 'country_name' => 'Thailand', 'country_code' => '+66', 'currency' => 'THB', 'currency_rate' => 0.029],
            ['shortcut' => 'TJ', 'country_name' => 'Tajikistan', 'country_code' => '+992', 'currency' => 'TJS', 'currency_rate' => 0.067],
            ['shortcut' => 'TK', 'country_name' => 'Tokelau', 'country_code' => '+690', 'currency' => 'NZD', 'currency_rate' => 0.022],
            ['shortcut' => 'TL', 'country_name' => 'Timor-Leste', 'country_code' => '+670', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'TM', 'country_name' => 'Turkmenistan', 'country_code' => '+993', 'currency' => 'TMT', 'currency_rate' => 0.29],
            ['shortcut' => 'TN', 'country_name' => 'Tunisia', 'country_code' => '+216', 'currency' => 'TND', 'currency_rate' => 0.032],
            ['shortcut' => 'TO', 'country_name' => 'Tonga', 'country_code' => '+676', 'currency' => 'TOP', 'currency_rate' => 0.43],
            ['shortcut' => 'TR', 'country_name' => 'Turkey', 'country_code' => '+90', 'currency' => 'TRY', 'currency_rate' => 0.039],
            ['shortcut' => 'TT', 'country_name' => 'Trinidad and Tobago', 'country_code' => '+1-868', 'currency' => 'TTD', 'currency_rate' => 0.15],
            ['shortcut' => 'TV', 'country_name' => 'Tuvalu', 'country_code' => '+688', 'currency' => 'AUD', 'currency_rate' => 0.015],
            ['shortcut' => 'TZ', 'country_name' => 'Tanzania', 'country_code' => '+255', 'currency' => 'TZS', 'currency_rate' => 0.00043],
            ['shortcut' => 'UA', 'country_name' => 'Ukraine', 'country_code' => '+380', 'currency' => 'UAH', 'currency_rate' => 0.11],
            ['shortcut' => 'UG', 'country_name' => 'Uganda', 'country_code' => '+256', 'currency' => 'UGX', 'currency_rate' => 0.00027],
            ['shortcut' => 'UM', 'country_name' => 'U.S. Minor Outlying Islands', 'country_code' => '+1', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'US', 'country_name' => 'United States', 'country_code' => '+1', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'UY', 'country_name' => 'Uruguay', 'country_code' => '+598', 'currency' => 'UYU', 'currency_rate' => 0.026],
            ['shortcut' => 'UZ', 'country_name' => 'Uzbekistan', 'country_code' => '+998', 'currency' => 'UZS', 'currency_rate' => 0.00009],
            ['shortcut' => 'VA', 'country_name' => 'Vatican City', 'country_code' => '+379', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'VC', 'country_name' => 'Saint Vincent and the Grenadines', 'country_code' => '+1-784', 'currency' => 'XCD', 'currency_rate' => 0.0037],
            ['shortcut' => 'VE', 'country_name' => 'Venezuela', 'country_code' => '+58', 'currency' => 'VES', 'currency_rate' => 0.0011],
            ['shortcut' => 'VG', 'country_name' => 'British Virgin Islands', 'country_code' => '+1-284', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'VI', 'country_name' => 'U.S. Virgin Islands', 'country_code' => '+1-340', 'currency' => 'USD', 'currency_rate' => 0.019],
            ['shortcut' => 'VN', 'country_name' => 'Vietnam', 'country_code' => '+84', 'currency' => 'VND', 'currency_rate' => 0.000043],
            ['shortcut' => 'VU', 'country_name' => 'Vanuatu', 'country_code' => '+678', 'currency' => 'VUV', 'currency_rate' => 0.017],
            ['shortcut' => 'WF', 'country_name' => 'Wallis and Futuna', 'country_code' => '+681', 'currency' => 'XPF', 'currency_rate' => 0.017],
            ['shortcut' => 'WS', 'country_name' => 'Samoa', 'country_code' => '+685', 'currency' => 'WST', 'currency_rate' => 0.43],
            ['shortcut' => 'YE', 'country_name' => 'Yemen', 'country_code' => '+967', 'currency' => 'YER', 'currency_rate' => 0.0015],
            ['shortcut' => 'YT', 'country_name' => 'Mayotte', 'country_code' => '+262', 'currency' => 'EUR', 'currency_rate' => 0.011],
            ['shortcut' => 'ZA', 'country_name' => 'South Africa', 'country_code' => '+27', 'currency' => 'ZAR', 'currency_rate' => 0.049],
            ['shortcut' => 'ZM', 'country_name' => 'Zambia', 'country_code' => '+260', 'currency' => 'ZMW', 'currency_rate' => 0.038],
            ['shortcut' => 'ZW', 'country_name' => 'Zimbabwe', 'country_code' => '+263', 'currency' => 'ZWL', 'currency_rate' => 0.013],
        ];
    }
}
